version: '3.8'

services:
  app:
    user: $UID:$GID
    build:
      context: .
    command: >
         sh -c "python manage.py wait_for_db &&
         python manage.py migrate &&
         python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./appdata:/appdata
      - ./data/web:/vol/web
    environment:
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=dev_db
      - DB_USER=dev_user
      - DB_PASS=haha_pass
    depends_on:
      - db
    
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=dev_db
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=haha_pass

    container_name: portfolio_app


volumes:
    appdata: