# Generated by Django 3.2.10 on 2021-12-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='featured',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
