# Generated by Django 3.2.12 on 2022-02-23 13:56

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20220127_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='comment',
            field=markdownx.models.MarkdownxField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
