# Generated by Django 3.2.12 on 2022-03-10 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20220223_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_posted'], 'verbose_name_plural': 'Posts'},
        ),
    ]
