# Generated by Django 3.2.8 on 2021-10-16 14:21

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('resume', models.FileField(null=True, upload_to=core.models.post_image_file_path)),
            ],
        ),
    ]
