# Generated by Django 3.2.8 on 2021-10-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_id',
            field=models.CharField(default='ABC', max_length=120, unique=True),
        ),
    ]
